spring.application.name=api-gateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Enable service discovery
spring.cloud.gateway.server.webmvc.discovery.locator.enabled=true
spring.cloud.gateway.server.webmvc.discovery.locator.lower-case-service-id=true

# Route to Auth Service
spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**